apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "valkey-cluster-config-template-%s" .Chart.Version }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  annotations:
    {{- include "valkey.annotations" . | nindent 4 }}
data:
  redis.conf: |-
    {{- .Files.Get "config/valkey-cluster-config.tpl" | nindent 4 }}
